export const actionTypes = {
  START_GAME: 'START_GAME',
  PLAYER_GET_CARDS: 'PLAYER_GET_CARDS',
  ENEMY_GET_CARDS: 'ENEMY_GET_CARD',
  MAKE_BET: 'MAKE_BET',
  UPDATE_MONEY: 'UPDATE_MONEY',
  REMOVE_CARDS: 'REMOVE_CARDS',
  DOUBLE: 'DOUBLE',
  STAND: 'STAND',
  LOSE: 'LOSE',
  WIN: 'WIN'
}
