export const actionTypes = {
  USER_GET_CARDS: 'USER_GET_CARDS',
  ENEMY_GET_CARDS: 'ENEMY_GET_CARD',
  MAKE_BET: 'MAKE_BET',
  UPDATE_MONEY: 'UPDATE_MONEY',
  REMOVE_CARDS: 'REMOVE_CARDS',
  DOUBLE: 'DOUBLE',
  STAND: 'STAND',
  LOOSE: 'LOOSE'
}
